# Generated by Django 4.2.5 on 2023-09-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_image_like_alter_image_user_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
